import React from 'react';
import type { Metadata } from 'next';

import { Header } from '(shared)/components/layout/Header';

import { WithChildren } from '(shared)/types/common.types';

import { comfortaa, nunito } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: WithChildren) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${comfortaa.variable} flex flex-col justify-start h-screen`}
      >
        <Header />

        <main>{children}</main>
      </body>
    </html>
  );
}
