import React from 'react';
import type { Metadata } from 'next';

import { Header } from '(shared)/components/layout/Header';

import { WithChildren } from '(shared)/types/common.types';

import { comfortaa, nunito } from './fonts';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { Providers } from '(shared)/components/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: WithChildren) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${comfortaa.variable} flex h-full min-h-screen flex-col`}
      >
        <Providers>
          <Header />

          <main className="flex-grow" role="main">
            {children}
          </main>
          <Toaster position="top-center" reverseOrder={false} />
        </Providers>
      </body>
    </html>
  );
}
