import {
  VscNewFile,
  VscCalendar,
  VscEyeClosed,
  VscEye,
  VscShield,
  VscSignIn,
  VscEdit,
  VscSearch,
  VscSettings,
  VscTrash,
  VscHome,
  VscSignOut,
  VscArrowRight,
  VscClose,
} from 'react-icons/vsc';
import { CgSpinner } from 'react-icons/cg';

export const ICONS = {
  ADMIN: VscShield,
  CALENDAR: VscCalendar,
  CLOSE: VscClose,
  CLOSED_EYE: VscEyeClosed,
  CREATE: VscNewFile,
  DELETE: VscTrash,
  EDIT: VscEdit,
  HOME: VscHome,
  FILTER: VscSettings,
  LOGOUT: VscSignOut,
  LOGIN: VscSignIn,
  OPENED_EYE: VscEye,
  READ_MORE: VscArrowRight,
  SEARCH: VscSearch,
  SPINNER: CgSpinner,
};
